# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.


#le numero de port que tomcat utilisera
server.port=9070
#Cr\u00e9e la base de donn\u00e9es si elle n'existe
spring.jpa.hibernate.ddl-auto=update
#Information de connexion
spring.datasource.url=jdbc:mysql://localhost/bd_stocker
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.jdbc.Driver