version: '2'
services:
    webstocker-app:
        image: webstocker
        external_links:
            - webstocker-mysql:mysql
            - webstocker-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/webstocker?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    webstocker-mysql:
        extends:
            file: mysql.yml
            service: webstocker-mysql
    webstocker-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: webstocker-elasticsearch
